user@ubuntu:~$ pwd
/home/user
user@ubuntu:~$ cd A3
bash: cd: A3: No such file or directory
user@ubuntu:~$ cd Desktop
user@ubuntu:~/Desktop$ cd A3
user@ubuntu:~/Desktop/A3$ make target=writerProc
g++ -c -o writerProc.o -MMD -MF .writerProc.d -Wall -Wextra -g writerProc.cpp
writerProc.cpp: In function ‘int main()’:
writerProc.cpp:30:5: error: ‘gets’ was not declared in this scope
     gets(str);
     ^~~~
writerProc.cpp:30:5: note: suggested alternative: ‘fgets’
     gets(str);
     ^~~~
     fgets
Makefile:15: recipe for target 'writerProc.o' failed
make: *** [writerProc.o] Error 1
user@ubuntu:~/Desktop/A3$ ls -l
total 108
-rw-r--r-- 1 user user   237 Oct 15 09:52 Makefile
-rwxr-xr-x 1 user user 34608 Oct 17 21:17 readerProc
-rw-r--r-- 1 user user  2422 Oct 17 21:33 readerProc.cpp
-rw-r--r-- 1 user user 41248 Oct 17 21:17 readerProc.o
-rw-r--r-- 1 user user  1976 Oct 15 09:53 sharedMem.cpp
-rw-r--r-- 1 user user   674 Oct 15 09:54 simpleSignal.cpp
-rw-r--r-- 1 user user   217 Oct 15 09:53 usingFtok.cpp
-rw-r--r-- 1 user user  1194 Oct 15 09:53 usingSemaphores.cpp
-rw-r--r-- 1 user user   690 Oct 17 21:33 writerProc.cpp
user@ubuntu:~/Desktop/A3$ ./readerProc 
sem_t=0x7fa7992ef000
shmID:753672
...tick 2830...
...tick 2830...
...tick 2830...
...tick 2830...
...tick 2830...
^C
user@ubuntu:~/Desktop/A3$ ls -l
total 108
-rw-r--r-- 1 user user   237 Oct 15 09:52 Makefile
-rwxr-xr-x 1 user user 34608 Oct 17 21:17 readerProc
-rw-r--r-- 1 user user  2422 Oct 17 21:33 readerProc.cpp
-rw-r--r-- 1 user user 41248 Oct 17 21:17 readerProc.o
-rw-r--r-- 1 user user  1976 Oct 15 09:53 sharedMem.cpp
-rw-r--r-- 1 user user   674 Oct 15 09:54 simpleSignal.cpp
-rw-r--r-- 1 user user   217 Oct 15 09:53 usingFtok.cpp
-rw-r--r-- 1 user user  1194 Oct 15 09:53 usingSemaphores.cpp
-rw-r--r-- 1 user user   690 Oct 17 21:33 writerProc.cpp
user@ubuntu:~/Desktop/A3$ ./readerProc 
sem_t=0x7f3e80d65000
shmID:753672
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
...tick 2850...
^C
user@ubuntu:~/Desktop/A3$ ./readerProc 
sem_t=0x7f8329b73000
shmID:753672
...tick 2851...
...tick 2851...
...tick 2851...
^Z
[1]+  Stopped                 ./readerProc
user@ubuntu:~/Desktop/A3$ bg
[1]+ ./readerProc &
...tick 2851...
user@ubuntu:~/Desktop/A3$ ...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
sign...tick 2851...
al ...tick 2851...
-US...tick 2851...
R1...tick 2851...
 ...tick 2851...
28...tick 2851...
51...tick 2851...

signal: command not found
user@ubuntu:~/Desktop/A3$ ...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...
...tick 2851...

[1]+  User defined signal 1   ./readerProc
user@ubuntu:~/Desktop/A3$ 
user@ubuntu:~/Desktop/A3$ 
user@ubuntu:~/Desktop/A3$ 
user@ubuntu:~/Desktop/A3$ 
user@ubuntu:~/Desktop/A3$ fg
bash: fg: current: no such job
user@ubuntu:~/Desktop/A3$ ./readerProc 
sem_t=0x7f63ae131000
shmID:753672
...tick 2888...
...tick 2888...
...tick 2888...
...tick 2888...
...tick 2888...
...tick 2888...
...tick 2888...
...tick 2888...
User defined signal 1
user@ubuntu:~/Desktop/A3$ cd
user@ubuntu:~$ pwd
/home/user
user@ubuntu:~$ ls
Desktop    Downloads         Music     Public  Templates
Documents  examples.desktop  Pictures  snap    Videos
user@ubuntu:~$ touch ipc.key
user@ubuntu:~$ ls
Desktop    Downloads         ipc.key  Pictures  snap       Videos
Documents  examples.desktop  Music    Public    Templates
user@ubuntu:~$ make target=readerProc
make: *** No targets specified and no makefile found.  Stop.
user@ubuntu:~$ ls
Desktop    Downloads         ipc.key  Pictures  snap       Videos
Documents  examples.desktop  Music    Public    Templates
user@ubuntu:~$ cd Desktop
user@ubuntu:~/Desktop$ cd A3
user@ubuntu:~/Desktop/A3$ make target=readerProc
g++ -c -o readerProc.o -MMD -MF .readerProc.d -Wall -Wextra -g readerProc.cpp
readerProc.cpp: In function ‘int main()’:
readerProc.cpp:20:14: error: ‘getpid’ was not declared in this scope
  pid_t pid = getpid();
              ^~~~~~
readerProc.cpp:20:14: note: suggested alternative: ‘pid’
  pid_t pid = getpid();
              ^~~~~~
              pid
readerProc.cpp:21:2: error: expected primary-expression before ‘:’ token
  :
  ^
readerProc.cpp:30:56: error: no match for ‘operator=’ (operand types are ‘sem_t’ and ‘sem_t*’)
  sem = sem_open("/tmpsem", O_CREAT|O_EXCL, RWRR, INTVAL);
                                                        ^
In file included from /usr/include/semaphore.h:28:0,
                 from readerProc.cpp:5:
/usr/include/x86_64-linux-gnu/bits/semaphore.h:40:3: note: candidate: constexpr sem_t& sem_t::operator=(const sem_t&)
 } sem_t;
   ^~~~~
/usr/include/x86_64-linux-gnu/bits/semaphore.h:40:3: note:   no known conversion for argument 1 from ‘sem_t*’ to ‘const sem_t&’
/usr/include/x86_64-linux-gnu/bits/semaphore.h:40:3: note: candidate: constexpr sem_t& sem_t::operator=(sem_t&&)
/usr/include/x86_64-linux-gnu/bits/semaphore.h:40:3: note:   no known conversion for argument 1 from ‘sem_t*’ to ‘sem_t&&’
readerProc.cpp:34:2: error: expected ‘)’ before ‘shmid’
  shmid = shmget(key, 1024, 0666 |  IPC_CREAT);
  ^~~~~
readerProc.cpp:37:24: error: ‘shmat’ was not declared in this scope
  shm_buffer = (char *) shmat(shmid, (void *) 0, 0);
                        ^~~~~
readerProc.cpp:37:24: note: suggested alternative: ‘shmid’
  shm_buffer = (char *) shmat(shmid, (void *) 0, 0);
                        ^~~~~
                        shmid
readerProc.cpp:42:3: error: ‘sleep’ was not declared in this scope
   sleep( 1 );
   ^~~~~
readerProc.cpp: In function ‘void sig_usr1(int)’:
readerProc.cpp:49:16: error: cannot convert ‘sem_t’ to ‘sem_t*’ for argument ‘1’ to ‘int sem_wait(sem_t*)’
  sem_wait( sem );
                ^
readerProc.cpp:60:16: error: cannot convert ‘sem_t’ to ‘sem_t*’ for argument ‘1’ to ‘int sem_post(sem_t*)’
  sem_post( sem );
                ^
readerProc.cpp:47:20: warning: unused parameter ‘signo’ [-Wunused-parameter]
 void sig_usr1( int signo ) {
                    ^~~~~
Makefile:15: recipe for target 'readerProc.o' failed
make: *** [readerProc.o] Error 1
user@ubuntu:~/Desktop/A3$ make target=readerProc
g++ -c -o readerProc.o -MMD -MF .readerProc.d -Wall -Wextra -g readerProc.cpp
readerProc.cpp: In function ‘void sig_usr1(int)’:
readerProc.cpp:75:19: warning: unused parameter ‘signo’ [-Wunused-parameter]
 void sig_usr1(int signo ){
                   ^~~~~
readerProc.cpp: In function ‘int main()’:
readerProc.cpp:84:8: warning: variable ‘sem’ set but not used [-Wunused-but-set-variable]
  sem_t sem = call_sem_open();
        ^~~
readerProc.cpp:87:6: warning: unused variable ‘shmId’ [-Wunused-variable]
  int shmId = getShmId();
      ^~~~~
readerProc.cpp: At global scope:
readerProc.cpp:18:13: warning: ‘void sig_usr(int)’ defined but not used [-Wunused-function]
 static void sig_usr( int signo ) {
             ^~~~~~~
g++ -o readerProc readerProc.o -pthread
user@ubuntu:~/Desktop/A3$ ./readerProc
sem_t=0x7faed5edf000
shmID:1015818
...tick 3173...
...tick 3173...
...tick 3173...
...tick 3173...
...tick 3173...
^C
user@ubuntu:~/Desktop/A3$ make target=readerTake3-2.cpp
make: *** No rule to make target 'readerTake3-2.cpp.o', needed by 'readerTake3-2.cpp'.  Stop.
user@ubuntu:~/Desktop/A3$ make target=readerTake3-2.cpp
make: *** No rule to make target 'readerTake3-2.cpp.o', needed by 'readerTake3-2.cpp'.  Stop.
user@ubuntu:~/Desktop/A3$ make target=readerTake32.cpp
make: *** No rule to make target 'readerTake32.cpp.o', needed by 'readerTake32.cpp'.  Stop.
user@ubuntu:~/Desktop/A3$ make target=readerTake32
g++ -c -o readerTake32.o -MMD -MF .readerTake32.d -Wall -Wextra -g readerTake32.cpp
g++ -o readerTake32 readerTake32.o -pthread
user@ubuntu:~/Desktop/A3$ ./readerTake32
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...
...tick...(3229)...

...tick...(3229)...
...tick...(3229)...
...tick...(3229)...

...tick...(3229)...
^C
user@ubuntu:~/Desktop/A3$ ^C
user@ubuntu:~/Desktop/A3$ 
